spring.application.name=UniversityManagementSystem
server.port=8080
server.servlet.context-path=/api

#database
spring.datasource.url=jdbc:postgresql://localhost:5432/universityDB
spring.datasource.username=postgres
spring.datasource.password=root

# Hibernate (JPA) Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#admin
admin.username=${ADMIN_USERNAME}
admin.password=${ADMIN_PASSWORD}